##############################################################
#                                                            #
# Xeon(R) + FPGA AFU Simulation Environment                  #
# File generated by ase/scripts/generate_ase_environment.py  #
#                                                            #
##############################################################

SIMULATOR ?= QUESTA

DUT_VLOG_SRC_LIST = /homes/varungohil/Dagger/hw/b/vlog_files.list 

ASE_PLATFORM ?= FPGA_PLATFORM_DISCRETE

