//
// Generated by afu_json_mgr from /homes/varungohil/Dagger/sw/../hw/rtl/ccip_std_afu.json
//

#ifndef __AFU_JSON_INFO__
#define __AFU_JSON_INFO__

#define AFU_ACCEL_NAME "cci_hello"
#define AFU_ACCEL_UUID "26B40788-034B-4389-B3C1-51A1B62ED6C2"
#define AFU_IMAGE_POWER 0
#define AFU_TOP_IFC "ccip_std_afu"

#endif // __AFU_JSON_INFO__
