//
// Generated by afu_json_mgr from /homes/varungohil/Dagger/hw/rtl/ccip_std_afu_hssi.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "cci_hello"
`define AFU_ACCEL_UUID 128'h26b40788_034b_4389_b3c1_51a1b62ed6c2
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ccip_std_afu"

`endif // __AFU_JSON_INFO__
