/* MTI_DPI */

/*
 * Copyright 2002-2021 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


#ifndef MTI_INCLUDED_TYPEDEF_ase_cfg_t
#define MTI_INCLUDED_TYPEDEF_ase_cfg_t

typedef struct {
    int ase_mode;
    int ase_timeout;
    int ase_num_tests;
    int enable_reuse_seed;
    int ase_seed;
    int enable_cl_view;
    int usr_tps;
    int phys_memory_available_gb;
}  ase_cfg_t;

#endif

#ifndef MTI_INCLUDED_TYPEDEF_cci_pkt
#define MTI_INCLUDED_TYPEDEF_cci_pkt

typedef struct {
    int mode;
    int qw_start;
    int mdata;
    int intr_id;
    int64_t cl_addr;
    int64_t qword[8];
    int resp_channel;
    int success;
    int byte_en;
    int byte_start;
    int byte_len;
}  cci_pkt;

#endif

#ifndef MTI_INCLUDED_TYPEDEF_mmio_t
#define MTI_INCLUDED_TYPEDEF_mmio_t

typedef struct {
    int tid;
    int write_en;
    int width;
    int addr;
    int64_t qword[8];
    int resp_en;
}  mmio_t;

#endif


DPI_LINK_DECL DPI_DLLESPEC
int
ase_init();

DPI_LINK_DECL DPI_DLLESPEC
int
ase_instance_running();

DPI_LINK_DECL DPI_DLLESPEC
int
ase_listener();

DPI_LINK_DECL DPI_DLLESPEC
void
ase_ready();

DPI_LINK_DECL DPI_DLLESPEC
void
count_error_flag_pong(
    int flag);

DPI_LINK_DECL DPI_DLLESPEC
void
mmio_response(
    mmio_t* mmio_pkt);

DPI_LINK_DECL DPI_DLLESPEC
void
rd_memline_req_dex(
    cci_pkt* pkg);

DPI_LINK_DECL DPI_DLLESPEC
void
rd_memline_rsp_dex(
    cci_pkt* pkg);

DPI_LINK_DECL DPI_DLLESPEC
void
scope_function();

DPI_LINK_DECL DPI_DLLESPEC
int
start_simkill_countdown();

DPI_LINK_DECL DPI_DLLESPEC
void
sv2c_config_dex(
    const char* str);

DPI_LINK_DECL DPI_DLLESPEC
void
sv2c_script_dex(
    const char* str);

DPI_LINK_DECL DPI_DLLESPEC
void
sw_reset_response();

DPI_LINK_DECL DPI_DLLESPEC
void
update_glbl_dealloc(
    int flag);

DPI_LINK_DECL DPI_DLLESPEC
void
wr_memline_req_dex(
    cci_pkt* pkg);

DPI_LINK_DECL DPI_DLLESPEC
void
wr_memline_rsp_dex(
    cci_pkt* pkg);

DPI_LINK_DECL int
afu_softreset_trig(
    int init,
    int value);

DPI_LINK_DECL int
ase_config_dex(
    const ase_cfg_t* cfg_in);

DPI_LINK_DECL int
ase_reset_trig();

DPI_LINK_DECL int
buffer_msg_inject(
    int timestamp_en,
    const char* logstr);

DPI_LINK_DECL int
count_error_flag_ping();

DPI_LINK_DECL int
mmio_dispatch(
    int initialize,
    const mmio_t* mmio_pkt);

DPI_LINK_DECL int
run_clocks(
    int num_clks);

DPI_LINK_DECL int
simkill();

#endif 
